"""
intent_classifier/training_data.py
-----------------------------------
Training dataset for the JARVIS Iron Man helmet intent classifier.
Includes natural language variations, politeness wrappers, and common
speech-to-text phrasing.
"""

TRAINING_EXAMPLES = {
    "OPEN_HELMET": [
        "open helmet",
        "open the helmet",
        "open faceplate",
        "open the faceplate",
        "lift faceplate",
        "lift the faceplate",
        "lift visor",
        "lift the visor",
        "faceplate up",
        "visor up",
        "helmet up",
        "open up",
        "pop the mask",
        "open mask",
        "can you lift my faceplate",
        "can you open the faceplate",
        "please lift the visor",
        "please open the helmet",
        "can you open up",
        "jarvis lift faceplate",
        "jarvis open the visor",
        "raise faceplate",
        "raise the visor",
        "lift face plate",
        "open face plate",
    ],
    "CLOSE_HELMET": [
        "close helmet",
        "close the helmet",
        "close faceplate",
        "close the faceplate",
        "lower faceplate",
        "lower the faceplate",
        "lower visor",
        "lower the visor",
        "faceplate down",
        "visor down",
        "helmet down",
        "close mask",
        "mask down",
        "drop the mask",
        "can you close my faceplate",
        "can you lower the visor",
        "please close the helmet",
        "close up",
        "shut faceplate",
        "shut the visor",
        "jarvis close helmet",
        "jarvis lower faceplate",
        "lower face plate",
        "close face plate",
    ],
    "LIGHTS_ON": [
        "lights on",
        "turn on lights",
        "turn on the lights",
        "eyes on",
        "turn on eyes",
        "turn on eye lights",
        "illuminate eyes",
        "power on eyes",
        "can you turn on the lights",
        "please turn the lights on",
        "turn eyes on",
        "enable lights",
        "lights upfront",
        "jarvis lights on",
        "jarvis turn on eyes",
    ],
    "LIGHTS_OFF": [
        "lights off",
        "turn off lights",
        "turn off the lights",
        "eyes off",
        "turn off eyes",
        "turn off eye lights",
        "kill the lights",
        "power off eyes",
        "can you turn off the lights",
        "please turn the lights off",
        "turn eyes off",
        "disable lights",
        "kill lights",
        "jarvis lights off",
        "jarvis turn off eyes",
    ],
    "COMBAT_MODE": [
        "combat mode",
        "enter combat mode",
        "activate combat mode",
        "red eyes",
        "red lights",
        "go red",
        "threat detected",
        "attack mode",
        "battle mode",
        "engage combat mode",
        "can you enter combat mode",
        "jarvis combat mode",
        "switch to combat mode",
        "set eyes to red",
    ],
    "PARTY_MODE": [
        "party mode",
        "enter party mode",
        "activate party mode",
        "rainbow lights",
        "rainbow eyes",
        "disco mode",
        "start the party",
        "dance mode",
        "engage party mode",
        "can you start party mode",
        "jarvis party mode",
        "switch to party mode",
        "rainbow mode",
    ],
    "NORMAL_MODE": [
        "normal mode",
        "enter normal mode",
        "activate normal mode",
        "reset lights",
        "default mode",
        "standard mode",
        "standby mode",
        "cancel combat mode",
        "cancel party mode",
        "exit combat mode",
        "exit party mode",
        "can you reset to normal mode",
        "jarvis normal mode",
        "back to normal",
    ],
    "NONE": [
        "hello jarvis",
        "what is the weather today",
        "who won the game last night",
        "how are you doing",
        "tell me a joke",
        "what time is it",
        "who is mark ruffalo",
        "what is quantum mechanics",
        "play some music",
        "search the web for news",
        "calculate 25 times 4",
        "how far is the moon",
        "what is your name",
        "can you answer a question",
        "who created iron man",
        "what is an esp32",
        "how does a servo motor work",
        "tell me about yourself",
        "what can you do",
        "never mind",
        "testing one two three",
    ]
}